language: python

python:
    - "3.3"
    - "3.4"
    - "3.5"

install: 
    - pip install -r requirements/requirements.txt
    - pip install -r requirements/test-requirements.txt
    - pip install coveralls

script: 
    - nosetests
    - python setup.py test --addopts "-v --cov PYEVALB --cov-report term-missing"""

after_success:
    coveralls
