language: python

python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"

install: 
    - pip install -r requirements/requirements.txt
    - pip install -r requirements/test-requirements.txt

script: nosetests
